/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DiaButton {
        /**
          * Button Text
         */
        "buttontext": string;
        /**
          * Path to anything
         */
        "path": string;
        /**
          * Submit, Button,...
         */
        "type": string;
        /**
          * Color, BG, Hover,...
         */
        "variant": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDiaButtonElement extends Components.DiaButton, HTMLStencilElement {
    }
    var HTMLDiaButtonElement: {
        prototype: HTMLDiaButtonElement;
        new (): HTMLDiaButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dia-button": HTMLDiaButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DiaButton {
        /**
          * Button Text
         */
        "buttontext"?: string;
        /**
          * Path to anything
         */
        "path"?: string;
        /**
          * Submit, Button,...
         */
        "type"?: string;
        /**
          * Color, BG, Hover,...
         */
        "variant"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dia-button": DiaButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dia-button": LocalJSX.DiaButton & JSXBase.HTMLAttributes<HTMLDiaButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
